[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rfuns"
version = "0.1.0"
description = "Python implementations of common R base functions"
authors = [
  {name = "Jonathan Carroll", email = "pypkg@jcarroll.com.au"},
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Utilities"
]
keywords = ["R"]
license.file = "LICENSE"
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "ruff", "rpy2"]

[tool.setuptools.packages.find]
where = ["."]

[project.urls]
"Source" = "https://github.com/jonocarroll/rfuns"