from ._strings import (
    nchar,
    grepl,
    grep,
    gsub,
    sub,
    trimws,
    toupper,
    tolower,
    startsWith,
    endsWith,
    strsplit,
    substr,
    paste,
    paste0,
    chartr,
    nzchar,
    formatC,
)
from ._utils import vec
from ._vectors import (
    which,
    which_min,
    which_max,
    diff,
    cumsum,
    cumprod,
    cummax,
    cummin,
    rev,
    duplicated,
    setdiff,
    intersect,
    union,
    unique,
    seq_along,
    seq_len,
    seq,
    r_range,
)
from ._table import table, prop_table, margin_table
from ._math import (
    sign,
    trunc,
    ceiling,
    floor,
    sqrt,
    log,
    log2,
    log10,
    exp,
    abs,
    var,
    sd,
    mean,
    median,
    quantile,
    scale,
    round,
)
from ._inspect import head, tail, length, nrow, ncol, dim, summary, rstr
from ._functional import lapply, sapply, vapply, tapply, rapply, Filter, Map, Reduce
from ._files import list_files, file_exists, dir_exists, basename, dirname, file_path

__all__ = [
    # Strings
    "nchar",
    "grepl",
    "grep",
    "gsub",
    "sub",
    "trimws",
    "toupper",
    "tolower",
    "startsWith",
    "endsWith",
    "strsplit",
    "substr",
    "paste",
    "paste0",
    "chartr",
    "nzchar",
    "formatC",
    # Vectors
    "which",
    "which_min",
    "which_max",
    "diff",
    "cumsum",
    "cumprod",
    "cummax",
    "cummin",
    "rev",
    "duplicated",
    "setdiff",
    "intersect",
    "union",
    "unique",
    "seq_along",
    "seq_len",
    "seq",
    "vec",
    "r_range",
    # Table
    "table",
    "prop_table",
    "margin_table",
    # Math
    "sign",
    "trunc",
    "ceiling",
    "floor",
    "sqrt",
    "log",
    "log2",
    "log10",
    "exp",
    "abs",
    "var",
    "sd",
    "mean",
    "median",
    "quantile",
    "scale",
    "round",
    # Inspect
    "head",
    "tail",
    "length",
    "nrow",
    "ncol",
    "dim",
    "summary",
    "rstr",
    # Functional
    "lapply",
    "sapply",
    "vapply",
    "tapply",
    "rapply",
    "Filter",
    "Map",
    "Reduce",
    # Files
    "list_files",
    "file_exists",
    "dir_exists",
    "basename",
    "dirname",
    "file_path",
]
